package uk.co.primaltech.stockmanagement.GUI.product;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import uk.co.primaltech.stockmanagement.GUI.main.MainWindow;

/**
 *
 * @author Nuno Mogas <nuno.mogas@gmail.com>
 */
public class SoldAction extends javax.swing.JDialog {

    private static volatile SoldAction instance = null;

    public static SoldAction getInstance() {
        if (instance == null) {
            synchronized (SoldAction.class) {
                if (instance == null) {
                    instance = new SoldAction();
                }
            }
        }
        return instance;
    }
    
    private final MouseListener buttonMouseListener = new MouseAdapter() {
        
    };
        

    private SoldAction() {
        initComponents();

        setModal(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setDefaultLookAndFeelDecorated(true);

        /* Center the window. */
        setLocationRelativeTo(null);

        /* Not resize window allowed */
        setResizable(false);

        jNewClient.setText("");
        jLoadClient.setText("");

        URL newClientURL = MainWindow.class.getResource("/new.png");
        ImageIcon newClientICON = new ImageIcon(Toolkit.getDefaultToolkit().getImage(newClientURL).getScaledInstance(40, 40, 100));
        jNewClient.setIcon(newClientICON);
        jLoadClient.setName("0");
        jNewClient.setText("<html><b>Creates a new client. </b> <br />This action connect the product a new client<br /> and auto-generate an invoice</html>");
        jNewClient.setHorizontalTextPosition(JLabel.TRAILING);
        jNewClient.addMouseListener(buttonMouseListener);

        URL loadClientURL = MainWindow.class.getResource("/load.png");
        ImageIcon loadClientICON = new ImageIcon(Toolkit.getDefaultToolkit().getImage(loadClientURL).getScaledInstance(40, 40, 100));
        jLoadClient.setIcon(loadClientICON);
        jLoadClient.setName("1");
        jLoadClient.setText("<html><b>Loads an existing client. </b> <br />This action connect the product to the existing client<br /> and auto-generate an invoice</html>");
        jLoadClient.setHorizontalTextPosition(JLabel.TRAILING);
        jLoadClient.addMouseListener(buttonMouseListener);

    }                

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLoadClient = new javax.swing.JLabel();
        jNewClient = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Action");
        setMaximumSize(new java.awt.Dimension(310, 170));
        setMinimumSize(new java.awt.Dimension(310, 170));
        setModal(true);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(290, 170));
        jPanel1.setMinimumSize(new java.awt.Dimension(290, 170));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLoadClient.setText("jLabel1");

        jNewClient.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Choose an option");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNewClient, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jLoadClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLoadClient, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLoadClient;
    private javax.swing.JLabel jNewClient;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
